import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[colors]
cursor = { cursor = "#ebdbb2", text = "#282828" }

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { family = "Iosevka Nerd Font Mono", style = "Regular" }
italic = { family = "Iosevka Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "Italic" }
size = 16

[window]
decorations = "none"
dynamic_padding = true
opacity = 1.0
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/opt/homebrew/bin/zsh"
args = ["-l", "-c", "/opt/homebrew/bin/tmux new-session -A -s base"]

[keyboard]
bindings = [
    { key = "A", mods = "Command", chars = "\u0001" },
    { key = "B", mods = "Command", chars = "\u0002" },
    { key = "C", mods = "Command", chars = "\u0003" },
    { key = "D", mods = "Command", chars = "\u0004" },
    { key = "E", mods = "Command", chars = "\u0005" },
    { key = "F", mods = "Command", chars = "\u0006" },
    { key = "M", mods = "Command", chars = "\u000D" },
    { key = "R", mods = "Command", chars = "\u0012" },
    { key = "S", mods = "Command", chars = "\u0013" },
    { key = "T", mods = "Command", chars = "\u0014" },
    { key = "U", mods = "Command", chars = "\u0015" },
    { key = "W", mods = "Command", chars = "\u0017" },
    { key = "X", mods = "Command", chars = "\u0017" },
    { key = "Y", mods = "Command", chars = "\u0019" },
    { key = "Z", mods = "Command", chars = "\u001A" },
    { key = "Enter", mods = "Shift", chars = "\u001b5" },
    { key = "Tab", mods = "Shift", chars = "\u001b`" },
    { key = "Period", mods = "Command", chars = "\u001b8" },
    { key = "Comma", mods = "Command", chars = "\u001b7" },
    { key = "Slash", mods = "Command", chars = "\u001b4" },
    { key = "I", mods = "Alt", chars = "\u001b0" },
    { key = "O", mods = "Alt", chars = "\u001b1" },
    { key = "Semicolon", mods = "Command", chars = "\u001b_" },

    # <C-i> mapped through Karabiner
    { key = "Left", mods = "Alt|Command", chars = "\u001b+" },

    # <C-o> mapped through Karabiner
    { key = "Right", mods = "Alt|Command", chars = "\u001b3" },

    # <C-n> mapped through Karabiner
    { key = "Left", mods = "Alt", chars = "\u001bb" },

    # <C-m> mapped through Karabiner
    { key = "Right", mods = "Alt", chars = "\u001bf" },
]
