#!/bin/bash

if [[ -x ".git/hooks/post-commit" ]]; then
  .git/hooks/post-commit
fi

if [[ -z "$ASK_TO_CREATE_JIRA_ISSUE" ]]; then
  exit
fi

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

exec < /dev/tty

branch=$(git branch --show-current)
subject=$(git log -1 --pretty=%s)
body=$(git log -1 --pretty=%b)

if [[ "$body" =~ "Summarize the change" ]]; then
  body="$(echo "$body" | sed '0,/Summarize the change/d' | sed '/## Notes for QA/,$d' | sed -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba')"
fi

if ! [[ "$subject" =~ ^[A-Z]+-[0-9]+ ]] && ! [[ "$branch" =~ [A-Z]+-[0-9]+$ ]]; then
  echo "Not on a JIRA branch and no JIRA ticket specified in commit message."
  echo -n "Would you like to auto-create a JIRA issue? [y/n] "
  read result
  if [[ "$result" == "y" ]]; then
    ticket_id=$(create-jira-issue -s "$subject" -d "$body")
    chmod -x "$script_dir/post-commit"
git commit --amend --no-verify -q -m "$ticket_id $subject

$body"
    chmod +x "$script_dir/post-commit"
  fi
fi
