cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'homebrew/cask-fonts'
brew 'mas'

brew 'coreutils'
brew 'diff-so-fancy'
brew 'fzf'
brew 'gcc'
brew 'git'
brew 'jq'
brew 'neovim'
brew 'nodenv'
brew 'pyenv'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'shellcheck'
brew 'tmux'
brew 'wget'
brew 'yarn', args: ['without-node']
brew 'z'
brew 'zsh'

# cask 'alfred' skip for now since I'm on version 3
cask 'appcleaner'
cask 'bartender'
cask 'caffeine'
cask 'dash'
cask 'dashlane'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'font-iosveka'
cask 'google-chrome'
cask 'hammerspoon'
cask 'iterm2'
cask 'java'
cask 'ngrok'
cask 'postgres'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlstephen'
cask 'quicklook-json'
cask 'spectacle'
cask 'spotify'
cask 'steermouse'
cask 'sublime-text'
cask 'tableplus'
cask 'the-unarchiver'
cask 'virtualbox'
cask 'vlc'

mas 'Bear', id: 1091189122
mas 'Numbers', id: 409203825
mas 'Reeder', id: 880001334
mas 'Spark', id: 1176895641
mas 'Things', id: 904280696
mas 'Xcode', id: 497799835
mas 'Lightshot Screenshot', id: 526298438
